name: build-test-deploy-reuseable
on: push
jobs:
  build-test-deploy-reuseable:
    # Importing a reusable workflow from another repository and branch
    uses: ViewPortMedia/vpm-github-workflows/.github/workflows/build-test-deploy.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
      
